"""test

Revision ID: 7c94963b0d82
Revises: cff70f0d70ab
Create Date: 2024-06-20 14:39:48.770356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c94963b0d82'
down_revision: Union[str, None] = 'cff70f0d70ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'epic_user', ['email'])
    op.drop_column('staff_user', 'role_staff')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_user', sa.Column('role_staff', postgresql.ENUM('management', 'support', 'commercial', name='role_staff_enum'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'epic_user', type_='unique')
    # ### end Alembic commands ###
