"""Added new field to model

Revision ID: e544f6300fb4
Revises: 
Create Date: 2024-05-31 16:46:54.932202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e544f6300fb4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    status_contract = sa.Enum('To sign', 'Signed', 'Cancelled', name='status_contract')
    status_contract.create(op.get_bind())    
    op.execute("ALTER TABLE epic_contract ALTER COLUMN status TYPE status_contract USING status::text::status_contract")    
    op.alter_column('epic_contract', 'status',
               existing_type=postgresql.ENUM('To sign', 'Signed', 'Cancelled', name='contract_status'),
               type_=sa.Enum('To sign', 'Signed', 'Cancelled', name='status_contract'),
               existing_nullable=True)
    op.add_column('staff_user', sa.Column('email', sa.String(), nullable=True))
    role_staff_enum = sa.Enum('management', 'support', 'commercial', name='role_staff_enum')
    role_staff_enum.create(op.get_bind())
    op.add_column('staff_user', sa.Column('role_staff', role_staff_enum, nullable=True))
    op.add_column('staff_user', sa.Column('password', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'staff_user', ['email'])
    op.drop_column('staff_user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE epic_contract ALTER COLUMN status TYPE contract_status USING status::text::contract_status")
    status_contract = sa.Enum('To sign', 'Signed', 'Cancelled', name='status_contract')
    status_contract.drop(op.get_bind())
    op.add_column('staff_user', sa.Column('role', postgresql.ENUM('management', 'support', 'commercial', name='user_role'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'staff_user', type_='unique')
    op.drop_column('staff_user', 'password')
    op.drop_column('staff_user', 'role_staff')
    op.drop_column('staff_user', 'email')
    role_staff_enum = sa.Enum('management', 'support', 'commercial', name='role_staff_enum')
    role_staff_enum.drop(op.get_bind())
    op.alter_column('epic_contract', 'status',
               existing_type=sa.Enum('To sign', 'Signed', 'Cancelled', name='status_contract'),
               type_=postgresql.ENUM('To sign', 'Signed', 'Cancelled', name='contract_status'),
               existing_nullable=True)
    # ### end Alembic commands ###
